apiVersion: v1
kind: Service
metadata:
  name: freebail-frontend
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31961
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: freebail-frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
