apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: freebail-wedding-api
  name: freebail-wedding-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: freebail-wedding-api
  template:
    metadata:
      labels:
        app: freebail-wedding-api
    spec:
      serviceAccountName: {{ include "freebail-wedding.serviceAccountName" . }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - freebail-wedding-api
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: freebail-db-creds
                  key: url
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freebail-mail-creds
                  key: password
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: freebail-mail-creds
                  key: username
            - name: RACK_ENV
              value: production
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: freebail-rails-master-key
                  key: key
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          name: freebail-wedding-api
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
        - command:
            - /cloud_sql_proxy
            - -instances=freebail-wedding:europe-west2:freebail-wedding=tcp:5432
            - -credential_file=/secrets/cloudsql/credentials.json
          image: "{{ .Values.cloudSql.image.repository }}:{{ .Values.cloudSql.image.tag }}"
          name: cloudsql-proxy
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: freebail-cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: freebail-cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
