{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: freebail-ingress
spec:
  rules:
  - host: freebail.wedding
    http:
      paths:
      - backend:
          service:
            name: freebail-frontend
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
      - backend:
          service:
            name: freebail-wedding-api
            port:
              number: 3000
        path: /api/
        pathType: ImplementationSpecific
  - host: admin.freebail.wedding
    http:
      paths:
      - backend:
          service:
            name: phpmyadmin
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - freebail.wedding
    - admin.freebail.wedding
    secretName: freebail-tls
{{- end }}
