apiVersion: v1
data:
  host: {{ .Values.db.host | b64enc | quote }}
  port: {{ .Values.db.port | toString | b64enc | quote }}
  rootPw: {{ .Values.db.rootPw | b64enc | quote }}
  url: {{ .Values.db.url | b64enc | quote }}
kind: Secret
metadata:
  name: freebail-db-creds
type: Opaque
