apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: phpmyadmin
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
